# Generated by Django 3.0.5 on 2020-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0005_auto_20200409_0906'),
        ('users', '0010_auto_20200408_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, to='gameexch.Game'),
        ),
    ]
