# Generated by Django 3.0.5 on 2020-04-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0003_auto_20200406_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={},
        ),
    ]
