# Generated by Django 3.0.5 on 2020-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0007_auto_20200418_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='message',
            field=models.TextField(max_length=240),
        ),
    ]
