# Generated by Django 3.0.5 on 2020-04-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0008_auto_20200418_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomment',
            name='number',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='number',
        ),
    ]
