# Generated by Django 3.0.5 on 2020-04-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0009_auto_20200418_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertogame',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameexch.Currency'),
        ),
        migrations.AlterField(
            model_name='usertogame',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
