# Generated by Django 3.0.5 on 2020-04-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0010_auto_20200430_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertogame',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
