# Generated by Django 3.0.7 on 2020-11-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0003_platform_ravg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='ravg_id',
            new_name='rawg_id',
        ),
    ]
