# Generated by Django 3.0.7 on 2020-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0004_auto_20201107_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
