# Generated by Django 3.0.7 on 2020-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0005_auto_20201107_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40, null=True)),
                ('rawg_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AlterField(
            model_name='platform',
            name='rawg_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
