# Generated by Django 3.0.7 on 2020-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0006_auto_20201107_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='gameexch.Genre'),
        ),
    ]
