# Generated by Django 3.0.7 on 2020-11-09 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameexch', '0007_auto_20201107_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='liked_by',
            field=models.ManyToManyField(related_name='user_liked_game_comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='liked_by',
            field=models.ManyToManyField(related_name='user_liked_user_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
