# Generated by Django 3.0.7 on 2020-11-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0009_auto_20201109_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameComment',
        ),
    ]
