# Generated by Django 3.0.7 on 2020-11-09 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameexch', '0010_delete_gamecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(related_name='user_liked_comment_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
