# Generated by Django 3.0.7 on 2020-11-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0011_auto_20201109_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=5),
        ),
    ]
