# Generated by Django 3.0.7 on 2020-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0013_auto_20201109_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=15),
        ),
    ]
