# Generated by Django 3.0.5 on 2020-04-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameexch', '0003_auto_20200406_1325'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('user',)},
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gameexch.City'),
        ),
        migrations.AddField(
            model_name='profile',
            name='consoles',
            field=models.ManyToManyField(to='gameexch.Console'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_telegramm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
