# Generated by Django 3.0.5 on 2020-04-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200407_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='consoles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_telegramm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='has_whatsapp',
        ),
        migrations.AddField(
            model_name='profile',
            name='telegramm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
