# Generated by Django 3.0.5 on 2020-04-07 13:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200407_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegramm',
            field=phone_field.models.PhoneField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=phone_field.models.PhoneField(blank=True, max_length=20, null=True),
        ),
    ]
